repos:
  - repo: https://github.com/Aldo-f/thuis.git
    docs_dir: docs
    # Optional: specify branch, default is master
    # branch: main
  - repo: https://github.com/Aldo-f/01-core-infra.git
    docs_dir: docs
    # Optional: specify branch, default is master
    # branch: main
