title: Aldo++;
email: info@aldofieuw.com
description: Portfolio made with Jekyll
baseurl: ''
url: 'https://aldo-f.github.io/'
twitter_username: __Chil__
github_username: Aldo-f
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
