site_name: Aldo's Documentation Hub
site_url: https://aldo-f.github.io
repo_url: https://github.com/Aldo-f/Aldo-f.github.io
repo_name: Aldo-f/Aldo-f.github.io
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      primary: indigo
      accent: pink
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.share
plugins:
  - search
  - multirepo:
      config_file: .multirepo.yml
nav:
  - Home: docs/index.md
  - Thuis: https://aldo-f.github.io/thuis/
  - Core Infrastructure: https://aldo-f.github.io/01-core-infra/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Aldo-f
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/aldo-fieuw
