site_name: Aldo Fieuw Documentation
site_url: https://aldo-f.github.io
repo_url: https://github.com/Aldo-f/Aldo-f.github.io
repo_name: Aldo-f/Aldo-f.github.io
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - navigation.sections
    - toc.follow
    - toc.integrate
plugins:
  - search
  - multirepo:
      config_file: .multirepo.yml
nav:
  - Home: docs/index.md
  - Thuis: https://aldo-f.github.io/thuis/
  - Core Infra: https://aldo-f.github.io/01-core-infra/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Aldo-f
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/aldo-fieuw
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@aldo_fieuw
markdown_extensions:
  - toc:
      permalink: true
