#!/usr/bin/env python3
"""Generate the blog categories-overview page (docs/blog/category/index.md).

The bundled Material blog plugin creates one page per category but no overview
listing all categories with post counts (checked in plugin source 9.7.7). This
script derives that overview deterministically from the post files themselves,
so it never drifts as long as it is re-run after adding/changing posts
(the verification harness fails the build pipeline if the committed copy is
stale).

Rules:
- drafts (front matter `draft: true`) are excluded, matching production builds
- output is sorted alphabetically (case-insensitive) and contains NO timestamps
  => byte-stable across runs, diff-friendly
- slugs follow Material's scheme: lowercase, non-alphanumeric runs -> '-'
"""

from __future__ import annotations

import datetime
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
POSTS_DIR = REPO / "docs" / "blog" / "posts"
OUT_FILE = REPO / "docs" / "blog" / "category" / "index.md"


def parse_front_matter(path: Path) -> dict | None:
    """Minimal YAML-front-matter reader for the flat post format."""
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n", text, re.DOTALL)
    if not match:
        return None
    meta: dict = {"categories": []}
    in_categories = False
    for line in match.group(1).splitlines():
        stripped = line.strip()
        if stripped.startswith("- ") and in_categories:
            meta["categories"].append(stripped[2:].strip())
            continue
        in_categories = False
        if ":" not in stripped:
            continue
        key, _, value = stripped.partition(":")
        key = key.strip().lower()
        value = value.strip()
        if key == "categories" and not value:
            in_categories = True
        elif key in {"title", "date", "draft"}:
            meta[key] = value.strip("'\"")
    return meta


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def main() -> int:
    if not POSTS_DIR.is_dir():
        print(f"ERROR: {POSTS_DIR} missing", file=sys.stderr)
        return 1

    counts: dict[str, int] = {}
    skipped = []
    for post in sorted(POSTS_DIR.glob("*.md")):
        meta = parse_front_matter(post)
        if meta is None:
            skipped.append((post.name, "no front matter"))
            continue
        if meta.get("draft", "").lower() == "true":
            continue  # excluded from production builds -> exclude here too
        date_raw = meta.get("date")
        try:
            datetime.date.fromisoformat((date_raw or "")[:10])
        except ValueError:
            skipped.append((post.name, f"invalid date {date_raw!r}"))
            continue
        for cat in meta.get("categories") or ["Uncategorized"]:
            counts[cat] = counts.get(cat, 0) + 1

    lines = [
        "# Categories",
        "",
        "All topics covered on this blog, newest-first inside each category.",
        "",
        "| Category | Posts |",
        "|----------|------:|",
    ]
    for name in sorted(counts, key=lambda n: n.lower()):
        lines.append(f"| [{name}]({slugify(name)}/) | {counts[name]} |")
    lines += [
        "",
        "Or browse [everything chronologically](../index.md).",
        "",
        "<!-- generated by scripts/gen_category_index.py -- DO NOT EDIT -->",
        "",
    ]
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(lines), encoding="utf-8")

    print(f"wrote {OUT_FILE.relative_to(REPO)} ({len(counts)} categories)")
    for name in sorted(counts):
        print(f"  {name}: {counts[name]}")
    for fname, why in skipped:
        print(f"  SKIPPED {fname}: {why}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
