#!/usr/bin/env python3
"""Generate per-language blog category overview pages.

For every existing language root under docs/<lang>/, this script derives
docs/<lang>/blog/category/index.md from that language's post files:

    docs/en/blog/posts/*.md  ->  docs/en/blog/category/index.md
    docs/nl/blog/posts/*.md  ->  docs/nl/blog/category/index.md

Rules:
- drafts (`draft: true`) are excluded, matching production builds
- output sorted alphabetically (case-insensitive), NO timestamps
  => byte-stable across runs, diff-friendly; the verification harness
  fails when the committed copy is stale
- slugs follow Material's scheme: lowercase, non-alphanumeric runs -> '-'
"""

from __future__ import annotations

import datetime
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def parse_front_matter(path: Path) -> dict | None:
    """Minimal YAML-front-matter reader for the flat post format."""
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n", text, re.DOTALL)
    if not match:
        return None
    meta: dict = {"categories": []}
    in_categories = False
    for line in match.group(1).splitlines():
        stripped = line.strip()
        if stripped.startswith("- ") and in_categories:
            meta["categories"].append(stripped[2:].strip())
            continue
        in_categories = False
        if ":" not in stripped:
            continue
        key, _, value = stripped.partition(":")
        key = key.strip().lower()
        value = value.strip().strip("'\"")
        if key == "categories" and not value:
            in_categories = True
        elif key in {"title", "date", "draft"}:
            meta[key] = value
    return meta


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def collect(posts_dir: Path) -> tuple[dict[str, int], list[tuple[str, str]]]:
    counts: dict[str, int] = {}
    skipped: list[tuple[str, str]] = []
    for post in sorted(posts_dir.glob("*.md")):
        meta = parse_front_matter(post)
        if meta is None:
            skipped.append((post.name, "no front matter"))
            continue
        if meta.get("draft", "").lower() == "true":
            continue  # excluded from production builds -> exclude here too
        date_raw = meta.get("date")
        try:
            datetime.date.fromisoformat((date_raw or "")[:10])
        except ValueError:
            skipped.append((post.name, f"invalid date {date_raw!r}"))
            continue
        for cat in meta.get("categories") or ["Uncategorized"]:
            counts[cat] = counts.get(cat, 0) + 1
    return counts, skipped


def render(counts: dict[str, int]) -> str:
    lines = [
        "# Categories",
        "",
        "All topics covered on this blog, newest-first inside each category.",
        "",
        "| Category | Posts |",
        "|----------|------:|",
    ]
    for name in sorted(counts, key=lambda n: n.lower()):
        lines.append(f"| [{name}]({slugify(name)}/) | {counts[name]} |")
    lines += [
        "",
        "Or browse [everything chronologically](../index.md).",
        "",
        "<!-- generated by scripts/gen_category_index.py -- DO NOT EDIT -->",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    roots = sorted(
        p for p in REPO.glob("docs/*/blog/posts")
        if p.is_dir()
    )
    if not roots:
        print("ERROR: no docs/<lang>/blog/posts directories found", file=sys.stderr)
        return 1

    failures = 0
    for posts_dir in roots:
        lang_root = posts_dir.parent.parent  # docs/<lang>
        counts, skipped = collect(posts_dir)
        out_file = lang_root / "blog" / "category" / "index.md"
        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_text(render(counts), encoding="utf-8")

        rel = out_file.relative_to(REPO)
        print(f"wrote {rel} ({len(counts)} categories)")
        for name in sorted(counts):
            print(f"  {name}: {counts[name]}")
        for fname, why in skipped:
            print(f"  SKIPPED {rel}:{fname}: {why}")
            failures += 1
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
